// flow-typed signature: 0280676947197db6b27cae30ec82c916
// flow-typed version: <<STUB>>/basicauth-middleware_v^2.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'basicauth-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'basicauth-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'basicauth-middleware/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'basicauth-middleware/index' {
  declare module.exports: $Exports<'basicauth-middleware'>;
}
declare module 'basicauth-middleware/index.js' {
  declare module.exports: $Exports<'basicauth-middleware'>;
}
declare module 'basicauth-middleware/test/index.js' {
  declare module.exports: $Exports<'basicauth-middleware/test/index'>;
}
